"""empty message

Revision ID: fcf5153533fb
Revises:
Create Date: 2026-02-04 23:16:22.990346

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf5153533fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'activity',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('depth', sa.SmallInteger(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.CheckConstraint('depth BETWEEN 1 AND 3', name=op.f('ck_activity_activity_depth_check')),
        sa.ForeignKeyConstraint(['parent_id'], ['activity.id'], name=op.f('fk_activity_parent_id_activity')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_activity')),
    )
    op.create_index(op.f('ix_activity_id'), 'activity', ['id'], unique=False)
    op.create_index(op.f('ix_activity_name'), 'activity', ['name'], unique=True)
    op.create_index(op.f('ix_activity_parent_id'), 'activity', ['parent_id'], unique=False)
    op.create_table(
        'building',
        sa.Column('address', sa.String(length=512), nullable=False),
        sa.Column(
            'location',
            geoalchemy2.types.Geometry(
                geometry_type='POINT',
                srid=4326,
                dimension=2,
                from_text='ST_GeomFromEWKT',
                name='geometry',
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_building')),
    )
    op.create_index(
        'idx_building_location', 'building', ['location'], unique=False, postgresql_using='gist', if_not_exists=True
    )
    op.create_index(op.f('ix_building_address'), 'building', ['address'], unique=True)
    op.create_index(op.f('ix_building_id'), 'building', ['id'], unique=False)
    op.create_table(
        'organization',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('building_id', sa.BigInteger(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['building_id'], ['building.id'], name=op.f('fk_organization_building_id_building'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_organization')),
    )
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=True)
    op.create_table(
        'organization_activity_association',
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('activity_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ['activity_id'],
            ['activity.id'],
            name=op.f('fk_organization_activity_association_activity_id_activity'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['organization_id'],
            ['organization.id'],
            name=op.f('fk_organization_activity_association_organization_id_organization'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_activity_association')),
    )
    op.create_index(
        op.f('ix_organization_activity_association_activity_id'),
        'organization_activity_association',
        ['activity_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_organization_activity_association_id'), 'organization_activity_association', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_organization_activity_association_organization_id'),
        'organization_activity_association',
        ['organization_id'],
        unique=False,
    )
    op.create_table(
        'organization_phone_number',
        sa.Column('phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['organization_id'],
            ['organization.id'],
            name=op.f('fk_organization_phone_number_organization_id_organization'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_phone_number')),
    )
    op.create_index(op.f('ix_organization_phone_number_id'), 'organization_phone_number', ['id'], unique=False)
    op.create_index(op.f('ix_organization_phone_number_phone'), 'organization_phone_number', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_phone_number_phone'), table_name='organization_phone_number')
    op.drop_index(op.f('ix_organization_phone_number_id'), table_name='organization_phone_number')
    op.drop_table('organization_phone_number')
    op.drop_index(
        op.f('ix_organization_activity_association_organization_id'), table_name='organization_activity_association'
    )
    op.drop_index(op.f('ix_organization_activity_association_id'), table_name='organization_activity_association')
    op.drop_index(
        op.f('ix_organization_activity_association_activity_id'), table_name='organization_activity_association'
    )
    op.drop_table('organization_activity_association')
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_table('organization')
    op.drop_index(op.f('ix_building_id'), table_name='building')
    op.drop_index(op.f('ix_building_address'), table_name='building')
    op.drop_index('idx_building_location', table_name='building', postgresql_using='gist')
    op.drop_table('building')
    op.drop_index(op.f('ix_activity_parent_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_name'), table_name='activity')
    op.drop_index(op.f('ix_activity_id'), table_name='activity')
    op.drop_table('activity')
    # ### end Alembic commands ###
